### ISSUE TITLE
Segfault when ED_MODE is NORMAL, Jhflag !=0 and MPI is used

### ISSUE THREAD

**Issue by lcrippa** [aamaricci/EDIpack2.0#5]
Hi, as per title.

I did some debugging and perhaps I found the culprit: in the file H_non_local.f90, version "stored", at lines 42(44) and 75(77) the code reads

`call sp_insert_element(MpiComm,spH0nd,htmp,j,i)`

if the indices i and j are inverted, the issue is not manifesting. For reference, in the nonsu2 code the interaction H is similarly constructed (as far as I gather) and at lines 80(82)  and 112(114) the code reads 

`call sp_insert_element(MpiComm,spH0,htmp,i,j)`

As far as I can see, i and j represent the same indices in both cases and the operators are applied in the same way.
May it be that in the first case i and j are swapped in the function call?

**Comment by lcrippa** [comment]
Edit: I think is indeed the case, because in the EDIpack version the indices are swapped

**Comment by aamaricci** [comment]
Ok, I try to reconstruct the issue. 
As far as I recall the swapped indices are there because at some point we realized (in the ED_NONSU2 channel) that the H build in the code is actually the transposed one (should be related to  a technicality of the sparse matrices). 
Thus we acted to correct this, which is of course relevant only in the Hermitian case where H^T = H^*.
In all the other cases H^T = H (real symmetric) so no issues arise from swapping i and j.

**Comment by aamaricci** [comment]
Addup: 
as you are hands on can you fix the bug and commit?

**Comment by lcrippa** [comment]
Wait, I'm a bit confused. I remember being there when we found out the swapped indices point, but that was for the hopping matrix I think (unless I remember something else). In this particular case, the code in LIB_DMFT_ED (or EDIpack 2) and that in EDIpack differ because the indices are swapped. I would tend to trust the second more... also because the first segfaults.

I will commit a fix, but I need some more debug first, because there seems to be something wrong when the Arpack method is selected and JHflag is true. Instead Lanczos works fine

**Comment by aamaricci** [comment]
I,J is the correct one. 
The only point would be save the conjg of a complex entry if any. In the ED_NORMAL H is real symmetric so no other changes are required.

**Comment by lcrippa** [comment]
Fixed in latest commit
